# Generated by Django 5.1.4 on 2024-12-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('a_name', models.CharField(blank=True, max_length=255, null=True)),
                ('a_address', models.CharField(blank=True, max_length=255, null=True)),
                ('a_contact', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'author',
            },
        ),
    ]
